language: php

php:
  - 7.1.11
  - 7.2
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1.11
    - php: 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
- vendor/bin/phpunit --verbose